export const PRICING_PLANS = [
  {
    id: 'solo',
    name: 'Solo',
    price: 5.99,
    unit: '/ month',
    users: '1 user · full features',
    trial: '3 months free',
    commitment: 'Month-to-month',
    highlight: false,
    features: [
      'All features included',
      'Unlimited meeting imports',
      'Action items & assignments',
      'Encrypted vault & email 2FA',
      'Fathom integration',
    ],
  },
  {
    id: 'team',
    name: 'Team',
    price: 3.99,
    unit: 'per user / month',
    users: '5–25 users',
    trial: '3 months free',
    commitment: 'Monthly or annual',
    highlight: true,
    badge: 'Most popular',
    features: [
      'Full features for every seat',
      'Multi-assignee action items',
      'Cross-user assignment inbox',
      'Shared folder organization',
      'Priority email support',
    ],
  },
  {
    id: 'business',
    name: 'Business',
    price: 2.99,
    unit: 'per user / month',
    users: '25–100 users',
    trial: '3 months free',
    commitment: '1-year minimum',
    volume: 'Volume discount',
    highlight: false,
    features: [
      'Full features at scale',
      'Company-wide commitment tracking',
      'Dedicated onboarding',
      'SLA-backed support',
      'Annual billing',
    ],
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: null,
    unit: 'custom pricing',
    users: '100+ users',
    trial: 'Pilot available',
    commitment: '1-year minimum',
    volume: 'Up to 40% volume discount',
    highlight: false,
    features: [
      'Everything in Business',
      'Custom contracts & invoicing',
      'Dedicated success manager',
      'Custom integrations',
    ],
  },
];
